---
# external roles and collections to download
# install: ansible-galaxy install -r requirements.yml

collections:
  - 'community.general'
  - 'ansible.posix'
  - 'community.mysql'
  - 'community.crypto'

roles:
  - src: 'anon8675309.infra_apache'
  - src: 'ansibleguy.infra_certs'
  - src: 'ansibleguy.infra_mariadb'
