---

- name: ZoneMinder | Debian | Installing dependencies
  ansible.builtin.apt:
    name: "{{ ZM_HC.packages.dependencies }}"
    state: present

- name: ZoneMinder | Debian | Installing dependencies
  ansible.builtin.apt:
    name: "{{ ZM_HC.packages.tools }}"
    state: present
  when: ZM_CONFIG.tools

- name: ZoneMinder | Debian | Adding repo-key
  ansible.builtin.apt_key:
    url: "{{ ZM_HC.repo_key }}"

- name: ZoneMinder | Debian | Adding package repository
  ansible.builtin.apt_repository:
    repo: "{{ ZM_HC.repo }}"
    state: present
    update_cache: yes
    filename: 'zoneminder'

- name: ZoneMinder | Debian | Managing database
  ansible.builtin.import_tasks: db.yml
  when: ZM_CONFIG.manage.db
  tags: [db]

- name: ZoneMinder | Debian | Unmanaged DB
  ansible.builtin.pause:
    prompt: "Since this role is not managing the zoneminder-database, you will need to import the database schema initially!
    This can be done like this when using a local database: 'cat {{ ZM_HC.database.schema_file }}
    | mysql --socket /run/mysqld/mysqld.sock -uroot -p {{ ZM_CONFIG.database.name }}'.
    Make sure the schema is imported before continuing!"
  when: not ZM_CONFIG.manage.db

- name: ZoneMinder | Debian | Managing webserver
  ansible.builtin.import_tasks: web.yml
  when: ZM_CONFIG.manage.webserver
  tags: [config]

- name: ZoneMinder | Debian | Unmanaged webserver
  ansible.builtin.pause:
    prompt: "Since this role is not managing the zoneminder-webserver, you will need to add its custom config as shown
    here: https://github.com/ZoneMinder/zoneminder/tree/master/misc"
  when: not ZM_CONFIG.manage.webserver

- name: ZoneMinder | Debian | Installing ZoneMinder
  ansible.builtin.apt:
    name: "{{ ZM_HC.packages.base }}"
    state: present

- name: ZoneMinder | Debian | Adding zoneminder config
   ansible.builtin.template:
    src: 'templates/etc/zm/conf.d/custom.conf.j2'
    dest: '/etc/zm/conf.d/custom.conf'
    owner: 'root'
    group: 'www-data'
    mode: 0640
  no_log: true

- name: ZoneMinder | Debian | Updating config-privileges
   ansible.builtin.file:
    path: '/etc/zm/zm.conf'
    state: file
    owner: 'root'
    group: 'www-data'
    mode: 0640

- name: ZoneMinder | Debian | Enabling/Starting service
   ansible.builtin.systemd:
    daemon_reload: yes
    name: 'zoneminder.service'
    enabled: yes
    state: started
